
    - name: Install PostgreSQL
      become: true
      apt:
        name: postgresql
        state: present
      notify: Create database user and database
        
    - name: Copy backup file to another server
      become: true
      copy:
        src: "{{ backup_file }}"
        dest: "{{ backup_file }}"
        remote_src: true
      notify: Restore database on another server
